const User = require('../models/User');

const generateMediId = (role) => {
    const randomNum = Math.floor(1000 + Math.random() * 9000);
    const prefixMap = {
        'PATIENT': 'PATI',
        'PHARMACY': 'PHA',
        'DOCTOR': 'DOC',
        'LAB': 'LAB',
        'HOSPITAL': 'HOSP',
        'BLOOD_BANK': 'BLOOD',
        'NURSE': 'NUR',
        'AMBULANCE': 'AMB',
    };
    const prefix = prefixMap[role] || role.substring(0, 4).toUpperCase();
    return `MS-${prefix}-${randomNum}`;
};

exports.getStats = async (req, res) => {
    try {
        const stats = {
            hospitals: await User.countDocuments({ role: 'HOSPITAL' }),
            labs: await User.countDocuments({ role: 'LAB' }),
            ambulances: await User.countDocuments({ role: 'AMBULANCE' }),
            pharmacies: await User.countDocuments({ role: 'PHARMACY' }),
            patients: await User.countDocuments({ role: 'PATIENT' }),
            doctors: await User.countDocuments({ role: 'DOCTOR' }),
            bloodBanks: await User.countDocuments({ role: 'BLOOD_BANK' }),
        };
        res.json(stats);
    } catch (err) {
        res.status(500).json({ success: false, message: err.message });
    }
};

exports.viewAll = async (req, res) => {
    try {
        const data = await User.find({ role: req.params.role });
        res.json(data);
    } catch (err) {
        res.status(500).json({ success: false, message: err.message });
    }
};

exports.addEntity = async (req, res) => {
    try {
        const { email, aadharNumber, role } = req.body;

        // --- DUPLICATE CHECK ---
        const lowerEmail = email ? email.toLowerCase() : null;
        const query = { $or: [] };
        if (lowerEmail) query.$or.push({ email: lowerEmail });
        if (aadharNumber) query.$or.push({ aadharNumber });

        if (query.$or.length > 0) {
            const existing = await User.findOne(query);
            if (existing) {
                return res.status(400).json({
                    success: false,
                    message: `User already exists with this ${existing.email === lowerEmail ? 'Email' : 'Aadhar'}`
                });
            }
        }

        const userRole = role || 'USER';
        const autoGeneratedId = generateMediId(userRole);
        const userData = new User({
            ...req.body,
            email: lowerEmail, // Normalize
            mediId: autoGeneratedId,
            role: userRole
        });
        await userData.save();
        res.json({
            success: true,
            message: `${userRole} Registered Successfully`,
            generatedId: autoGeneratedId
        });
    } catch (err) {
        res.status(500).json({ success: false, message: err.message });
    }
};

exports.deleteEntity = async (req, res) => {
    try {
        await User.findByIdAndDelete(req.params.id);
        res.json({ success: true, message: "Deleted Successfully" });
    } catch (err) {
        res.status(500).json({ success: false, message: err.message });
    }
};

exports.toggleStatus = async (req, res) => {
    try {
        const user = await User.findById(req.params.id);
        if (!user) return res.status(404).json({ success: false, message: "User not found" });

        user.status = user.status === 'blocked' ? 'active' : 'blocked';
        await user.save();

        res.json({ success: true, message: `Status updated to ${user.status}`, newStatus: user.status });
    } catch (err) {
        res.status(500).json({ success: false, message: err.message });
    }
};

exports.updateEntity = async (req, res) => {
    try {
        const { id } = req.params;
        const updateData = req.body;

        // Prevent changing core fields like role or mediId for safety
        delete updateData.role;
        delete updateData.mediId;

        const updated = await User.findByIdAndUpdate(id, updateData, { new: true });
        if (!updated) return res.status(404).json({ success: false, message: "User not found" });

        res.json({ success: true, message: "Record Updated Successfully", data: updated });
    } catch (err) {
        res.status(500).json({ success: false, message: err.message });
    }
};
